name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

cache-mode: read

jobs:
  format_lint:
    runs-on: ubuntu-latest
    name: format and lint
    steps:
      - uses: "actions/checkout@v7.0.1"
        name: checkout repo
      - uses: "pnpm/action-setup@v6.0.10"
        with:
          version: 11
          run_install: true
          cache: true
      - name: check format
        run: pnpm prettier --check .
      - name: check lint
        run: pnpm lint
  try_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: pnpm/setup@v2.0.2
        with:
          runtime: node@24
          version: ^12.0.0
          cache: true
      - run: |
          pnpm build
